export const products = [
  {
    id: 1,
    title: "Silver Iphone X With Airpods",
    description: "silver in color",
    price: "250",
    img: "https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
    quantity: 1,
  },
  {
    id: 2,
    title: "Turned-on Black Samsung Android Smartphone",
    description: "black in color",
    price: "230",
    img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
    quantity: 1,
  },
  {
    id: 3,
    title: "Oppo 9",
    description: "grey in color",
    price: "350",
    img: "https://image.shutterstock.com/image-photo/shenzhen-china-21-september-2020-600w-1818868982.jpg",
    quantity: 1,
  },
  {
    id: 4,
    title: "Oppo reno 12",
    description: "Best mobile ever",
    price: "905",
    img: "https://image.shutterstock.com/image-photo/bangkok-thailand-oppo-launch-new-600w-2042430113.jpg",
    quantity: 1,
  },
  {
    id: 5,
    title: "Samsung S21",
    description: "black in color",
    price: "250",
    img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    quantity: 1,
  },
  {
    id: 6,
    title: "Redmi 9",
    description: "black in color",
    price: "350",
    img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 7,
    title: "Iphone 8plus",
    description: "silver in color",
    price: "250",
    img: "https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
    quantity: 1,
  },
  {
    id: 8,
    title: "Iphone 12",
    description: "Best mobile ever",
    price: "900",
    img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 9,
    title: "Samsung S21",
    description: "black in color",
    price: "250",
    img: "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    quantity: 1,
  },
];
